routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ContactosController@index')->name('contactos');

Auth::routes();

Route::group(['middleware' => ['auth']], function () {

    Route::group(['prefix' => 'contactos'], function () {

        Route::get('create', 'ContactosController@create')->name('contactos.create');

        Route::get('edit/{id?}', 'ContactosController@edit')->name('contactos.edit');

        Route::post('edit/{id?}', 'ContactosController@store')->name('contactos.store');

        Route::get('delete/{id}', 'ContactosController@delete')->name('contactos.delete');

        //person
    });

    Route::resource('person', PersonController::class);

    
});

app/Person.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Person extends Model
{
    use SoftDeletes;

    public $table = "person";


    protected $fillable = ['id', 'name', 'email'];

    protected $casts = [
        'created_at' => 'datetime:d/m/Y',
        'updated_at' => 'datetime:d/m/Y',
    ];

    public function contactos() : HasMany
    {
        return $this->hasMany(Contacts::class, 'person_id');
    }

    public function getContactos()
    {
        return $this->equipas;
    }
}

app/Http/Controllers/PersonController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Repositories\Repository;
use App\Person;
use App\Contacts;
use App\Http\Requests\StorePersonn;
use Illuminate\Validation\Rule;
use Symfony\Component\HttpFoundation\Request;

class PersonController extends Controller
{
    public function __construct(Person $model)
    {
        $this->model = new Repository($model);
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $person = $this->model->all(null,9);

        return view('person.index')->with('person', $person);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $person = new Person();

        return view('person.edit', compact('person'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $id=null)
    {
        $validatedData = $request->validate([
            //'email' => 'required|email',
            'name' => 'required',
            'email' =>  [
                'email',
                'required', 
            ]
        ]);

        $request = $request->except('_token');

        if($id){
            $saved = $this->model->update($request, $id);
            $msg = "Contact updated";
        }else{
            $saved  = $this->model->create($request);
            $msg = "Contact created";
        }

        return redirect(route('person'))->with('success', $msg);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\equipas  $equipas
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $person = $this->model->find($id);

        $contactos = Contacts::where('person_id', $id)->get();

        return view('person.edit', compact(['person', 'contactos']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\equipas  $equipas
     * @return \Illuminate\Http\Response
     */


    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Equipas  $Equipas
     * @return \Illuminate\Http\Response
     */
    public function delete($id)
    {
        $model = $this->model->delete($id);

        return redirect()->back();
    }

}

resources/views/person/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br />
            @endif

            <div class="row">

                <form action="{{route('person.store', $person->id)}}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="name">Name</label>
                        <!-- <select class="countrycode form-control" name="countrycode" id="#countrycode">
                    </select> -->
                        <input type="text" class="form-control" name="name" id="name" value="{{$person->name}}">


                    </div>
                    <div class="form-group">
                        <label for="email">E-mail</label>
                        <input type="email" class="form-control" name="email" id="email" value="{{$person->email}}">

                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>

            </div>

            @if(isset($contactos))
            <div class="row mt-4">
                <table class="table table-striped mt-4">
                    <tr>
                        <th>ID</th>
                        <th>Country code</th>
                        <th>Number</th>
                        <th></th>
                        <th></th>
                    </tr>

                    @foreach($contactos as $item)
                    <tr>
                        <td>{{$item->id}}</td>
                        <td>{{$item->countrycode}}</td>
                        <td>{{$item->number}}</td>
                        <td><a href="{{route('contactos.edit', $item->id)}}">edit</a></td>
                        <td><a href="{{route('contactos.delete', $item->id)}}">delete</a></td>
                    </tr>
                    @endforeach


                </table>
            </div>
            @endif

        </div>
    </div>
</div>

@endsection

resources/views/person/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

        @if(session()->get('success'))
            <div class="alert alert-success">
            {{ session()->get('success') }}  
            </div>
        @endif

        <a href="{{route('person.create')}}" class="btn btn-primary">Create Person</a>
            
        <table class="table table-striped mt-4">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>E-mail</th>
                <th></th>
                <th></th>
            </tr>

            @foreach($person as $item)
            <tr>
                <td>{{$item->id}}</td>
                <td>{{$item->name}}</td>
                <td>{{$item->email}}</td>
                <td><a href="{{route('person.edit', $item->id)}}">edit</a></td>
                <td><a href="{{route('person.destroy', $item->id)}}">delete</a></td>
            </tr>
            @endforeach

            
        </table>
        </div>
    </div>
</div>
@endsection